;/*FB_PKG_DELIM*/

__d("PolarisHashtagHeaderActionButtonsQuery$Parameters",["PolarisHashtagHeaderActionButtonsQuery_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PolarisHashtagHeaderActionButtonsQuery_instagramRelayOperation"),metadata:{is_distillery:!0,root_field_name:["fetch__XDTTagInfo"]},name:"PolarisHashtagHeaderActionButtonsQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PolarisKeywordSearchExploreRoot.entrypoint",["JSResourceForInteraction","PolarisHashtagHeaderActionButtonsQuery$Parameters"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){var b=a.routeParams;a=a.routeProps;a=(a=a.q_override)!=null?a:b.q;b=(a==null?void 0:a.startsWith("#"))?a.substring(1):"";return{queries:{hashtagHeaderButtonsQueryReference:{parameters:c("PolarisHashtagHeaderActionButtonsQuery$Parameters"),variables:{tag_name:b}}}}},root:c("JSResourceForInteraction")("PolarisKeywordSearchExploreRoot.react").__setRef("PolarisKeywordSearchExploreRoot.entrypoint")};g["default"]=a}),98);
__d("PolarisProfileReelsTabContentQuery_instagramRelayOperation",[],(function(a,b,c,d,e,f){e.exports="24164713859812789"}),null);
__d("PolarisProfileReelsTabContentQuery$Parameters",["PolarisProfileReelsTabContentQuery_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PolarisProfileReelsTabContentQuery_instagramRelayOperation"),metadata:{is_distillery:!0,root_field_name:["xdt_api__v1__clips__user__connection_v2","xdt_viewer"]},name:"PolarisProfileReelsTabContentQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PolarisProfileReelsTabRoot.entrypoint",["JSResourceForInteraction","PolarisProfileReelsTabContentQuery$Parameters","buildPolarisProfileRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildPolarisProfileRoute.entrypoint")(c("JSResourceForInteraction")("PolarisProfileReelsTabRoot.react").__setRef("PolarisProfileReelsTabRoot.entrypoint"),function(a){a=a.routeProps;var b=a.id;a=a.number_of_preloaded_posts;return{queries:{contentQuery:{environmentProviderOptions:{preloaderGroup:"ig_web_profile_feed"},options:{},parameters:c("PolarisProfileReelsTabContentQuery$Parameters"),variables:{data:{include_feed_video:!0,page_size:(a=a)!=null?a:12,target_user_id:b}}}}}});g["default"]=a}),98);
__d("PolarisProfileTaggedTabContentQuery_instagramRelayOperation",[],(function(a,b,c,d,e,f){e.exports="29340426355603440"}),null);
__d("PolarisProfileTaggedTabContentQuery$Parameters",["PolarisProfileTaggedTabContentQuery_instagramRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("PolarisProfileTaggedTabContentQuery_instagramRelayOperation"),metadata:{is_distillery:!0,root_field_name:["xdt_api__v1__usertags__user_id__feed_connection"]},name:"PolarisProfileTaggedTabContentQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("PolarisProfileTaggedTabRoot.entrypoint",["JSResourceForInteraction","PolarisProfileTaggedTabContentQuery$Parameters","buildPolarisProfileRoute.entrypoint"],(function(a,b,c,d,e,f,g){"use strict";a=c("buildPolarisProfileRoute.entrypoint")(c("JSResourceForInteraction")("PolarisProfileTaggedTabRoot.react").__setRef("PolarisProfileTaggedTabRoot.entrypoint"),function(a){a=a.routeProps;return{queries:{contentQuery:{environmentProviderOptions:{preloaderGroup:"ig_web_profile_feed"},options:{},parameters:c("PolarisProfileTaggedTabContentQuery$Parameters"),variables:{count:12,user_id:a.id}}}}});g["default"]=a}),98);