;/*FB_PKG_DELIM*/

__d("UFI2UserActivityIdleTimeout",[],(function(a,b,c,d,e,f){"use strict";a=3e4;f["default"]=a}),66);
__d("CometUserActivityMonitor",["ErrorGuard","ExecutionEnvironment","SubscriptionsHandler","UFI2UserActivityIdleTimeout","UserActivity","Visibility"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=[],k=!1,l=(h||(h=c("ExecutionEnvironment"))).canUseDOM&&c("UserActivity").isOnTab()&&c("UserActivity").isActive(c("UFI2UserActivityIdleTimeout"))?"ACTIVE":"INACTIVE",m=[],n;function o(a){k=!0;m.push.apply(m,j);var b=function(){var b=m.shift();(i||(i=c("ErrorGuard"))).applyWithGuard(function(){return b(a)},null,[],{name:"CometUserActivityMonitor"})};while(m.length)b();k=!1}function p(a){var b=l;l=a;b!==a&&o(a)}function a(){return l}d=function(){n==null&&(n=new(c("SubscriptionsHandler"))(),n.addSubscriptions(c("UserActivity").subscribe(function(a,b){a=b.event;if(/^mouse(enter|leave|move|over|out)$/.test(a.type)&&c("UserActivity").isOnTab()===!1)return;p("ACTIVE")}),function(){var a=function(){p("INACTIVE")};window.addEventListener("blur",a,{passive:!0});return{remove:function(){return window.removeEventListener(a,{passive:!0})}}}(),c("Visibility").addListener(c("Visibility").HIDDEN,function(){p("INACTIVE")})))};function b(a){j.push(a);k&&m.push(a);var b=!1;return{remove:function(){if(b)return;var c=j.indexOf(a);c!==-1&&j.splice(c,1);if(k){c=m.indexOf(a);c!==-1&&m.splice(c,1)}b=!0}}}(h||(h=c("ExecutionEnvironment"))).canUseDOM&&d();g.getActivityState=a;g.init=d;g.subscribe=b}),98);
__d("CometVPVDUserActivityMonitor",["CometUserActivityMonitor"],(function(a,b,c,d,e,f,g){"use strict";a={isUserActive:function(){return d("CometUserActivityMonitor").getActivityState()==="ACTIVE"},subscribe:function(a){var b=d("CometUserActivityMonitor").subscribe(function(b){b=b==="ACTIVE";a&&a(b)});return function(){b&&b.remove()}}};g["default"]=a}),98);
__d("isIntersectionObserverEntryVPVDVisible",["intersectionObserverEntryIsIntersecting"],(function(a,b,c,d,e,f,g){"use strict";var h=200,i={height:0};function a(a,b){b===void 0&&(b=h);var d=c("intersectionObserverEntryIsIntersecting")(a);if(d===!1)return!1;d=a.boundingClientRect;var e=a.intersectionRect,f=a.rootBounds;d=d||i;e=e||i;f=f||i;return e.height>=b||e.height>=f.height/2||e.height===d.height||a.intersectionRatio>.95}g["default"]=a}),98);
__d("isIntersectionObserverEntryVPVDVisiblePct",["intersectionObserverEntryIsIntersecting"],(function(a,b,c,d,e,f,g){"use strict";var h=.5,i={height:0};function a(a,b){b===void 0&&(b=h);var d=c("intersectionObserverEntryIsIntersecting")(a);if(d===!1)return!1;d=a.intersectionRect;var e=a.rootBounds,f=a.boundingClientRect;if(f==null||f.height===0)return!1;d=d||i;e=e||i;return d.height/f.height>=b||d.height>=e.height/2||a.intersectionRatio>.95}g["default"]=a}),98);
__d("vpvdConstants",[],(function(a,b,c,d,e,f){"use strict";a=250;b=200;f.DEFAULT_MIN_VISIBLE_TIME_MS=a;f.DEFAULT_MIN_VISIBLE_PX=b}),66);
__d("useVPVDImpression",["CometVPVDUserActivityMonitor","cr:921407","isIntersectionObserverEntryVPVDVisible","isIntersectionObserverEntryVPVDVisiblePct","react","useVisibilityObserver","vpvdConstants"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useCallback;function a(a){var e=a.activityMonitorOverride,f=a.isLite,g=a.minVisiblePct,h=a.minVisiblePx;h=h===void 0?d("vpvdConstants").DEFAULT_MIN_VISIBLE_PX:h;var j=a.minVisibleTimeMs,k=j===void 0?d("vpvdConstants").DEFAULT_MIN_VISIBLE_TIME_MS:j,l=a.onVPVDEnd;j=a.onVPVDStart;a=b("cr:921407")();var m=a[0];a=a[1];var n=i(function(a){if(a.visibleDuration<k)return;l(a)},[k,l]),o=f===!0?1:h;h=i(function(a){return g!=null?c("isIntersectionObserverEntryVPVDVisiblePct")(a,g):c("isIntersectionObserverEntryVPVDVisible")(a,o)},[o,g]);f=f===!0?null:{thresholdOverride:"EXPENSIVE"};e=babelHelpers["extends"]({activityMonitorOverride:(e=e)!=null?e:c("CometVPVDUserActivityMonitor"),isEntryInViewport:h},f);h=c("useVisibilityObserver")({onHidden:n,onVisibilityDurationUpdated:a,onVisible:j,options:e});return[h,m]}g["default"]=a}),98);
__d("useNoopDebuggingInfoComponent",[],(function(a,b,c,d,e,f){"use strict";var g=function(){};function a(){return[null,g]}f["default"]=a}),66);